### ISSUE TITLE
getting this error

### ISSUE THREAD

**Issue by Robinxo** [WildCyclotron/MyAnimeList-discord-bot#2]
![image](https://user-images.githubusercontent.com/108807832/204091531-d6f619bf-d658-4776-86f1-950aec4d0d75.png)

**Comment by ym496** [comment]
The command's name is "image" and its alias is "**im**" not "img".

**Comment by Robinxo** [comment]
![image](https://user-images.githubusercontent.com/108807832/204243168-54ae4b17-5fc6-4ec6-acbe-0cc6ccac4ecd.png)
tried most of the commands getting the same error.

**Comment by ym496** [comment]
I see. The API might have changed some shit. After all, It's been more than a year since I updated anything. I recommend you to look into the [API](https://github.com/Rapptz/discord.py) and update the code accordingly.

**Comment by Robinxo** [comment]
yeah,that i don't really know python that much.
